export const TECHS = [
  { name: "React", logo: "/logos/react.png", highlight: true },
  { name: "Next.js", logo: "/logos/nextjs.png", highlight: true },
  { name: "TypeScript", logo: "/logos/typescript.png", highlight: true },
  { name: "Tailwind CSS", logo: "/logos/tailwindcss.png", highlight: true },
  { name: "JavaScript", logo: "/logos/javascript.png", highlight: false },
  { name: "PostgreSQL", logo: "/logos/postgresql.png", highlight: false },
  { name: "Figma", logo: "/logos/figma.png", highlight: false },
  { name: "Bootstrap", logo: "/logos/bootstrap.png", highlight: false },
  { name: "Express", logo: "/logos/express.png", highlight: false },
  { name: "GitHub", logo: "/logos/github.png", highlight: false },
  { name: "Axios", logo: "/logos/axios.png", highlight: false },
  { name: "Auth0", logo: "/logos/auth0.png", highlight: false },
  { name: "HTML", logo: "/logos/html.png", highlight: false },
  { name: "CSS", logo: "/logos/css.png", highlight: false },
  { name: "Stripe", logo: "/logos/stripe.png", highlight: false },
];